Repository CodeForAfrica/HURUmap, pull requests merged in 2018-09, with the labels that each got.

#22 Add 'Download' to chart options
  hurumap/static/js/charts.js
  hurumap/static/js/vendor/dom-to-image.min.js
  hurumap/templates/profile/profile_detail.html
Labels: enhancement

#27 Add request context processor
  hurumap/settings.py
Labels: bug

#30 Ensure GPLv3 is listed as license
  setup.py
Labels: bug, enhancement

#31 Add MANIFEST.in to HURUmap package
  CHANGELOG.md
  MANIFEST.in
Labels: enhancement

#26 Add ability to add source to charts
  hurumap/static/js/charts.js
  hurumap/templates/profile/profile_detail.html
Labels: enhancement

#33 Add dependency links
  setup.py
Labels: enhancement

#35 Add source to embeds and subtitle to all viz
  hurumap/static/js/charts.js
  hurumap/static/js/embed.chart.frame.js
  hurumap/templates/profile/profile_detail.html
Labels: bug, enhancement

#36 [Feature] Multiple Chart Qualifiers Support
  hurumap/static/js/charts.js
  hurumap/templates/profile/profile_detail.html
Labels: enhancement

#39 Ensure source link opens in a `_blank` target
  hurumap/static/js/charts.js
Labels: enhancement
