Repository CodeForAfrica/HURUmap, pull requests merged in 2019-02, with the labels that each got.

#53 Standardize .gitignore
  .gitignore
Labels: bug, enhancement

#52 Implement Mapit
  .env.example
  hurumap/mapit_geo.py
  hurumap/profiles/census.py
  hurumap/settings.py
  hurumap/static/js/map_mapit.js
  hurumap/static/js/profile_map_mapit.js
  hurumap/templates/homepage.html
  hurumap/templates/profile/profile_detail.html
  hurumap/templates/settings_js.html
Labels: enhancement

#54 Add Help Page
  hurumap/settings.py
  hurumap/templates/_base.html
  hurumap/templates/help.html
Labels: enhancement, good first issue

#55 Mapit Integration Tests
  fixtures/hurumap_fixtures.json
  fixtures/hurumap_ke.json
  hurumap/profiles/census.py
  hurumap/tests.py
Labels: enhancement, good first issue

#56 Upgrade to Django 1.11
  hurumap/profiles/census.py
  hurumap/settings.py
  hurumap/tables.py
  hurumap/urls.py
Labels: enhancement
