Repository CodeForAfrica/HURUmap, pull requests merged in 2019-03, with the labels that each got.

#58 Add missing `hurumap.dashboard`
  hurumap/dashboard/settings.py
Labels: bug

#60 Wagtail v2.0 Upgrade
  Dockerfile
  hurumap/dashboard/migrations/0001_initial.py
  hurumap/dashboard/models.py
  hurumap/dashboard/settings.py
  hurumap/dashboard/urls.py
  setup.py
Labels: enhancement

#62 Allow Customization of HURUmap Charts
  hurumap/settings.py
  hurumap/static/js/charts.js
  hurumap/templates/profile/profile_detail.html
  setup.py
Labels: enhancement

#64 Improve HURUmap.theme.charts setting
  hurumap/settings.py
  hurumap/static/js/charts.js
  hurumap/templates/profile/profile_detail.html
Labels: bug, enhancement
